language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
  - pip install pep8 pip-tools coviolations_app coverage
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage 2>test_result
notifications:
  email:
    - lcasassa@gmail.com
after_script:
  - coverage report
  - covio
