language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - nosetests test.py
notifications:
  email:
    - lcasassa@gmail.com
after_success:
  - nosetests --with-coverage test.py
